### ISSUE TITLE
Broken by Windows 11 update 22H2

### ISSUE THREAD

**Issue by ryan-preble** [MikeHotelOscar/AutoHotkey-Virtual-Desktops#1]
Updating to windows 11 version 22H2 causes functionalities to break. I have not done an in-depth look at what breaks, but I know that the higher-level functions like getting the current desktop number and moving the active window to another desktop no longer work with this update.

**Comment by MikeHotelOscar** [comment]
The update broke some of the functionality of the DLL file, I've added a couple to increase stability. Your issues should be resolved with the new file.
